Azure stack: Add samples under Hybrid
Azure-Samples/resource-manager-ruby-resources-and-groups pull request #13
Opened 2018-03-22 19:54 UTC by viananth

2018-03-23 01:02 UTC, bganapa requested changes

2018-03-23 01:02 UTC, bganapa commented on Hybrid/example.rb
> +      base_url: 'https://management.<location>.azurestack.external'
Example should be runnable as such against ASDK one node deployment. I think we should hardcode the location to be local in the example.rb

2018-03-23 01:02 UTC, bganapa commented on Hybrid/example.rb
> +      base_url: 'https://management.<location>.azurestack.external'
or base url could be a environment var just like tenant id

2018-03-23 01:02 UTC, bganapa commented on Hybrid/example.rb
> +      base_url: 'https://management.<location>.azurestack.external'
this comment is applicable for other samples as well

2018-03-23 01:02 UTC, bganapa commented on Hybrid/spec/example_spec.rb
> +require 'spec_helper'
Whats this file for?

2018-03-23 01:02 UTC, bganapa commented on Hybrid/example.rb
> +  settings.authentication_endpoint = 'https://login.windows.net/'
These should be read from ARM metadata endpoint.  On ADFS environment authentication_endpoint is diferent

2018-04-04 20:59 UTC, sarangan12 approved these changes

2018-04-04 21:00 UTC, merged